name: 01 - Building Blocks
on:
  # - push
  - workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: export a=123
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: say-goodbye
        run: echo "$a"
